# アップロードファイルサイズなど
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
spring.thymeleaf.cache=false

# Supabase(Postgres) 用データベース設定
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.xrrepkcfpqeeedwwupja
spring.datasource.password=s9hZEu4gCioGO30t
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# Gmail メール設定（そのまま）
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=t4st1289@gmail.com
spring.mail.password=mjmqmtcaueibzsug
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
